### ISSUE TITLE
Implement Forced DA Analysis

### ISSUE THREAD

**Issue by JoschD** [pylhc/PyLHC#18]

**Comment by mihofer** [comment]
Option 'XY' is not working for .. when merging the 2 df in row 511, the index is converted from object to Timestamp which later breaks in row 891 the plotting

**Comment by JoschD** [comment]
Add linear fit plot

**Comment by JoschD** [comment]
add config ini output

**Comment by JoschD** [comment]
Throw NotImplementedError for plane XY
