### ISSUE TITLE
SDDS update for llong

### ISSUE THREAD

**Issue by phbelang** [pylhc/PyLHC#2]
Hi, 

The new format for sdds files often uses llong format. I was able to use your code with the following modifications :
classes.py, line 17-19 : add llong format (>i8, 8, int)
reader.py line 139 : convert num_dims to int -> int(num_dims)

Thank you for the good work! Is there any plan to add ascii compatibility?

**Comment by JoschD** [comment]
Hey!
the sdds reader in this package was very old, as were most of the scripts in here.
For that reason, the package has now been repurposed for python3 tools.

For the sdds reader there is a way newer package available: https://github.com/pylhc/sdds
You can now also install it via pip.

Can you check if this supports your formats? And if not, please open an issue there.
ASCII is still not supported, but on the TODO-list.

Bests!
Josch

**Comment by phbelang** [comment]
Done! Thanks!
