### ISSUE TITLE
Update setup for consistency with pylhc packages

### ISSUE THREAD

**Issue by fsoubelet** [pylhc/PyLHC#41]
Would also be a good time to think about the dependencies' versions.

Since we're all fine with `pandas 1.x` in other packages, we probably shouldn't require `0.25.x` here.

**Comment by fsoubelet** [comment]
Seems like installing from [pyjapc's repo](https://gitlab.cern.ch/scripting-tools/pyjapc) is causing problems in CI, but the pyjapc on PyPI is very out-of-date.

Fix tbd

**Comment by JoschD** [comment]
@fsoubelet pls remove `setup.cfg`  🥺
